language: ruby
rvm:
  - 2.2.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
install: gem install github-pages html-proofer
script: jekyll build --trace && htmlproof _site --only-4xx --check-html --href-ignore '#,/jekyll-boilerplate/'
